packages:
  - projects/**

catalog:
  vitepress: ^1.6.3
  typescript: ^5.8.3
  vite: ^7.0.0
  vite-plugin-top-level-await: ^1.5.0
  vite-plugin-wasm: ^3.4.1
  "@picocss/pico": ^2.1.1
  sass: ^1.89.2

linkWorkspacePackages: true
