# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

name: "Login into the Docker CLI"
description: "Login into the Docker CLI with a predefined configuration"

inputs:
  github_access_token:
    required: true
    description: "The GitHub token to use in the action"

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 #v3.5.0
      with:
        registry: ghcr.io
        username: kutu-dev
        password: ${{ inputs.github_access_token }}

    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1
