name: "Setup Nix"
description: "Install Nix, use the local cache and install the packages listed in the default devShell"

inputs:
  github_token:
    required: true
    description: "A privileged GitHub token"

runs:
  using: "composite"

  steps:
    - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31.4.1
      with:
        github_access_token: "${{ inputs.github_access_token }}"

    - uses: DeterminateSystems/magic-nix-cache-action@17890a7757f4c985b8ea5057a77a931d7a8984b1 # v0.1.5
    - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
