# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

name: "Publish updates of all Rust crates"

permissions:
  contents: read

# If a new commit is pushed just ignore the current one in the process queue and skip to the newest one
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - "publish/*.*.*/*"

jobs:
  publish-crates:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, 'crates')

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: ./.github/actions/setup-nix
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: katyo/publish-crates@02cc2f1ad653fb25c7d1ff9eb590a8a50d06186b # v2
        with:
          registry-token: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
